## AuthLinc Configuration

# Service Configuration
service:
  name: AuthLinc
  version: 1.0.0
  description: LINC Agent for authentication and authorization

# API Configuration
api:
  port: 3003
  host: 0.0.0.0
  prefix: /agents/auth
  
# JWT Configuration
jwt:
  secret: ${JWT_SECRET:healthlinc-secret-key-change-in-production}
  algorithm: HS256
  access_token_expire_minutes: ${ACCESS_TOKEN_EXPIRE_MINUTES:60}
  refresh_token_expire_days: ${REFRESH_TOKEN_EXPIRE_DAYS:7}
  
# Authentication Providers
providers:
  - type: local
    enabled: true
  - type: oauth
    enabled: false
    providers:
      - name: google
        enabled: false
        client_id: ${GOOGLE_CLIENT_ID:}
        client_secret: ${GOOGLE_CLIENT_SECRET:}
      - name: microsoft
        enabled: false
        client_id: ${MS_CLIENT_ID:}
        client_secret: ${MS_CLIENT_SECRET:}

# Logging Configuration
logging:
  level: ${LOG_LEVEL:info}
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Security Configuration
security:
  password:
    min_length: 8
    require_upper: true
    require_lower: true
    require_digit: true
    require_special: true
  rate_limiting:
    enabled: true
    max_attempts: 5
    window_seconds: 300  # 5 minutes
  
# Audit Configuration
audit:
  enabled: true
  log_level: info
  store_days: 90
