# MatchLinc Agent Configuration

# Server configuration
server:
  host: 0.0.0.0
  port: 3006
  debug: true

# Security settings
security:
  jwt_secret: ${JWT_SECRET}
  token_expiry: 3600

# Validation configuration
validation:
  rules_source: "database"  # options: file, database
  confidence_threshold: 0.7  # minimum confidence to consider a match valid
  enable_ai_enhancement: true
  
# Training resources
training:
  resources_path: "/app/resources"
  update_interval: 86400  # seconds (1 day)
  
# External service connections
services:
  fhir_server:
    url: ${FHIR_SERVER_URL}
    timeout: 30
  auth_service:
    url: ${AUTH_SERVICE_URL}
    timeout: 10

# Logging configuration
logging:
  level: ${LOG_LEVEL}
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
