# ReviewerLinc Module Configuration

# Server configuration
server:
  host: 0.0.0.0
  port: 3007
  debug: true

# Security settings
security:
  jwt_secret: ${JWT_SECRET}
  token_expiry: 3600

# Fee schedule configuration
fee_schedules:
  data_source: "file"  # options: file, database
  default_storage_path: "data/fee_schedules.json"
  
# Contract management
contracts:
  data_source: "file"  # options: file, database
  default_storage_path: "data/contracts.json"
  
# Analysis configuration
analysis:
  benchmarks:
    - name: "medicare"
      source: "file"
      path: "data/medicare_rates.json"
    - name: "average"
      source: "computed"
    - name: "top_payer"
      source: "computed"
  refresh_interval: 86400  # seconds (1 day)
  
# External service connections
services:
  fhir_server:
    url: ${FHIR_SERVER_URL}
    timeout: 30
  auth_service:
    url: ${AUTH_SERVICE_URL}
    timeout: 10

# Logging configuration
logging:
  level: ${LOG_LEVEL}
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
