apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: brainsait-monitor
  labels:
    app: brainsait
spec:
  selector:
    matchLabels:
      app: brainsait
  endpoints:
  - port: web
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: brainsait
